### ISSUE TITLE
How to deploy code that has both react and nodejs applications

### ISSUE THREAD

**Issue by zhenujt** [SalarC123/Classius#12]
Can you share the deployment tutorial?

**Comment by SalarC123** [comment]
I deployed my backend server and my front end separately. I used Heroku to deploy my backend so I wouldn’t have to pay any money, but it limits my server usage per month unfortunately. It’s still a really good option, but you just need to use an uptime service that constantly pings the server to keep your server up because Heroku temporarily shuts it down for inactivity. Then, for the frontend, I used Netlify which is completely free and has no major restrictions. Watch this tutorial to learn how to deploy a MERN application: https://youtu.be/Z_D4w6HmT8k

The only thing it doesn’t mention is how to set up an uptime robot to ping your Heroku application
